### PR TITLE
Dev editprofile backend

### LINKED ISSUE #56: Edit Profile functionality: Profile information update API
## Context
Please review #53, #55 (Not required)

## Problem 
We need a API for update the user's profile information in the back end

## Solution 

- [ ] Create a function to update or upgrade ( [difference between put vs patch](https://rapidapi.com/blog/put-vs-patch/)  ) the profile information in the user model
- [ ] Create a controller function for the model function
- [ ] Create a route for the controller function 

## Note 
if need, the issue can be broken into two different issue one is for model and one is for controller and route

### LINKED ISSUE #58: Edit Profile functionality: Profile information update API testing
## Context
Please review #56 #53 

Blocked by #56
## Problem 
To test the Profile information update API we need to implement tests (unit test or regression testing)

## Solution 

- [ ] Create unit test for update function in the model 
- [ ] Create unit test for controller function (if need)
- [ ] Create regression testing to the API using jest

## Note 
**A issue may be created to research about JEST api testing and add the supertest library**

Each step in the solution can be a issue if needed. Issue should not be more than **3 hours**

### LINKED ISSUE #163: Documentation for Edit profile API
## Context
Edit profile API is used to update user information

## Problem
The Technical documentation of the API is needed 

## Solution 

- [ ] Create Documentation about how to setup the API (Overview of implementation details)
- [ ] Create Documentation about how to use the API (How to call the API )

### PR DESCRIPTION
**Pull request by jyaneshseeam**
# Pull Request name

Edit profile API ( backend)

## Source 
Closes #163  
Closes #56
Closes #58

## Description 

Edit profile API, receives updated user data, and updates it to the database
Test suite has been done
### Summary of PR  

API receives patch request and updates user data in database

### Purpose 

Updating user profile data

## Review and Testing Steps
- [ ] If you want just check tests if it passes in build , everything should be good, if you want to manually play around with the API, follow steps below
- [ ] Pull this branch
- [ ] Run  ``` cd app\server ```
- [ ] create a .env file and get the values from the shared doc from https://docs.google.com/document/d/1sprMBncWt9RDJSFmwBZRFc_Gg_Zg0lG9kvmOKvTmca8/edit
- [ ]  run ``` npm install```
- [ ] run ``` docker build -t server . ```
- [ ] run ``` docker run -dp 8080:8080 server ```
- [ ] open request.http file
- [ ] Login first, you will receive a token, use the token in header everytime you send request, see request.http for example
- [ ] PATCH http://localhost:8080/users/edit/contactinfo with example in request.http   to send patch request for contact info
- [ ] PATCH http://localhost:8080/users/edit/personalinfo with example in request.http   to send patch request for personal info

## Additional Information (If applicable)
Check app\documentation\editprofile.md for documentation of API

### Notes
you can use a tool like POSTMAN or a tool like Rest client

Copy and paste the request from request.http for Postman , or perform send request directly from that file for RestClient

### CODE REVIEW

**Comment by sontushkpaul** [comment]
@jyaneshseeam is there any API to get the user information for single user? Are we able to protect the API endpoint so that no one else can get the  personal information passing a valid token everytime the user fetch the information?

**Comment by sontushkpaul** [comment]
@jyaneshseeam "http://localhost:8080/emergency/create" endpoint must be protected and only the admin can use that.

**Comment by jyaneshseeam** [comment]
> @jyaneshseeam "http://localhost:8080/emergency/create" endpoint must be protected and only the admin can use that.

okay I will add an admin endpoint to that as middleware

**Comment by jyaneshseeam** [comment]
> @jyaneshseeam "http://localhost:8080/emergency/create" endpoint must be protected and only the admin can use that.

This has been done now, and code is pushed

**Comment by jyaneshseeam** [comment]
@sontushkpaul @DemiAdisa @ja-chisholm 
 If you want just check tests if it passes in build, everything should be good, if you want to manually play around with the API, follow the steps in the pr comment

File: app/server/account_management/controllers/user_management_controller.js [hunk 1]
```diff
@@ -140,10 +141,74 @@ const getUserList = async (req, res) => {
...
+            if (result.status == 200) {
+                res.status(200);
+                res.json(result.message);
+            } else if (result.status == 401) {
+                res.status(401);
+                res.json(result.message);
+            }
+    } catch (err) {
+        res.status(500);
+        res.json(err.meassage);
```
Comment (ja-chisholm) [inline app/server/account_management/controllers/user_management_controller.js]: I think this may be a typo so it wouldn't work, maybe change to err.message

File: app/server/account_management/controllers/user_management_controller.js [hunk 2]
```diff
@@ -140,10 +141,74 @@ const getUserList = async (req, res) => {
...
+            res.status(200);
+            res.json(result.message);
+        } else if (result.status == 401) {
+            res.status(401);
+            res.json(result.message);
+        }
+        
+    } catch (err) {
+        res.status(500);
+        res.json(err.meassage);
```
Comment (ja-chisholm) [inline app/server/account_management/controllers/user_management_controller.js]: same here

**Review by ja-chisholm — APPROVED** [review]

**Comment by jyaneshseeam** [comment]
@sontushkpaul  please review pr, changes you wanted is already done

File: app/server/account_management/controllers/user_management_controller.js [hunk 3]
```diff
@@ -163,11 +164,10 @@ const getUserList = async (req, res) => {
...
  */
  const updatePersonalInfo = async (req, res) => {
-        const User_id= req.params.id;
     
         try {
             const user = {
-                id: User_id,
+                id: req.user,
                 userFirstName:req.body.userFirstName,
                 userMiddleName: req.body.userMiddleName,
```
Comment (sontushkpaul) [inline app/server/account_management/controllers/user_management_controller.js:172]: What if there is  no middle name?

Comment (jyaneshseeam) [reply app/server/account_management/controllers/user_management_controller.js:172]: Then, front-end property for middle name would it would be null, and null would be passed or just empty string by using ""

Comment (sontushkpaul) [reply app/server/account_management/controllers/user_management_controller.js:172]: Okay

**Review by sontushkpaul — APPROVED** [review]
